In [4]:
class MotorImageryDataset:
    def __init__(self, dataset='C:/Users/USER/Downloads/A01T.npz'):
        if not dataset.endswith('.npz'):
            dataset += '.npz'

        self.data = np.load('C:/Users/USER/Downloads/A01T.npz')

        self.Fs = 250 # 250Hz from original paper

        # keys of data ['s', 'etyp', 'epos', 'edur', 'artifacts']

        self.raw = self.data['s'].T
        self.events_type = self.data['etyp'].T
        self.events_position = self.data['epos'].T
        self.events_duration = self.data['edur'].T
        self.artifacts = self.data['artifacts'].T

        # Types of motor imagery
        self.mi_types = {769: 'left', 770: 'right', 771: 'foot', 772: 'tongue', 783: 'unknown'}

    def get_trials_from_channel(self, channel=7):

        # Channel default is C3

        startrial_code = 768
        starttrial_events = self.events_type == startrial_code
        idxs = [i for i, x in enumerate(starttrial_events[0]) if x]

        trials = []
        classes = []
        for index in idxs:
            try:
                type_e = self.events_type[0, index+1]
                class_e = self.mi_types[type_e]
                classes.append(class_e)

                start = self.events_position[0, index]
                stop = start + self.events_duration[0, index]
                trial = self.raw[channel, start:stop]
                trials.append(trial)

            except:
                continue

        return trials, classes

datasetA1 = MotorImageryDataset()
trials, classes = datasetA1.get_trials_from_channel()
# trials contains the N valid trials, and clases its related class.

In [2]:
import numpy as np

In [6]:
[trials],[classes]

([[array([0.1953125 , 2.00195312, 2.29492188, ..., 6.68945312, 6.10351562,
          6.20117188]),
   array([-11.328125  ,  -9.91210938, -11.1328125 , ...,  -3.46679688,
           -2.58789062,   4.1015625 ]),
   array([ 9.91210938, 10.3515625 ,  0.5859375 , ..., 12.74414062,
          13.33007812,  8.93554688]),
   array([-10.00976562,  -8.3984375 ,  -8.64257812, ...,   0.29296875,
            3.125     ,   4.8828125 ]),
   array([ 2.19726562, -0.43945312,  4.63867188, ...,  2.63671875,
           1.31835938, -1.5625    ]),
   array([23.4375    , 23.68164062, 19.67773438, ...,  1.46484375,
           5.71289062,  9.81445312]),
   array([  8.49609375,  14.84375   ,  14.59960938, ..., -13.28125   ,
           -9.71679688,  -1.5625    ]),
   array([-13.28125   , -11.47460938, -14.40429688, ...,   0.34179688,
           -0.14648438,   0.390625  ]),
   array([-3.41796875, -9.52148438,  0.48828125, ...,  2.29492188,
          -5.078125  , -5.02929688]),
   array([-1.26953125,  0.43945312, -

In [7]:
class MotorImageryDataset:
    def __init__(self, dataset='C:/Users/USER/Downloads/A01E.npz'):
        if not dataset.endswith('.npz'):
            dataset += '.npz'

        self.data = np.load('C:/Users/USER/Downloads/A01E.npz')

        self.Fs = 250 # 250Hz from original paper

        # keys of data ['s', 'etyp', 'epos', 'edur', 'artifacts']

        self.raw = self.data['s'].T
        self.events_type = self.data['etyp'].T
        self.events_position = self.data['epos'].T
        self.events_duration = self.data['edur'].T
        self.artifacts = self.data['artifacts'].T

        # Types of motor imagery
        self.mi_types = {769: 'left', 770: 'right', 771: 'foot', 772: 'tongue', 783: 'unknown'}

    def get_trials_from_channel(self, channel=7):

        # Channel default is C3

        startrial_code = 768
        starttrial_events = self.events_type == startrial_code
        idxs = [i for i, x in enumerate(starttrial_events[0]) if x]

        trials = []
        classes = []
        for index in idxs:
            try:
                type_e = self.events_type[0, index+1]
                class_e = self.mi_types[type_e]
                classes.append(class_e)

                start = self.events_position[0, index]
                stop = start + self.events_duration[0, index]
                trial = self.raw[channel, start:stop]
                trials.append(trial)

            except:
                continue

        return trials, classes

datasetA1 = MotorImageryDataset()
trials, classes = datasetA1.get_trials_from_channel()
# trials contains the N valid trials, and clases its related class.

In [11]:
[trials],[classes]

([[array([-5.76171875, -6.29882812, -6.29882812, ...,  4.19921875,
           4.15039062, -1.70898438]),
   array([ -1.3671875 ,   0.34179688,   2.734375  , ...,  -9.32617188,
          -12.54882812,  -4.39453125]),
   array([-12.59765625, -23.4375    , -21.484375  , ...,  12.79296875,
            5.078125  ,   3.46679688]),
   array([ 1.26953125, -5.76171875,  0.53710938, ...,  1.953125  ,
           0.29296875, -3.7109375 ]),
   array([-14.94140625,  -6.20117188,  -7.71484375, ...,  -2.1484375 ,
           -7.03125   ,  -9.765625  ]),
   array([4.54101562, 6.59179688, 9.03320312, ..., 4.78515625, 1.85546875,
          5.95703125]),
   array([-13.0859375 , -17.7734375 , -11.86523438, ...,   8.0078125 ,
           11.76757812,   8.59375   ]),
   array([14.453125  , 15.625     , 26.31835938, ..., 21.92382812,
          26.3671875 , 26.80664062]),
   array([ -9.42382812, -13.18359375, -12.35351562, ...,  -2.24609375,
            0.53710938,   1.46484375]),
   array([ 1.171875  , -2.68554

In [1]:
dim(trials)

NameError: name 'dim' is not defined